root_dir: "data/ShapeNetCore_V5"

classes:
  - "02691156" # Airplane
  - "02958343" # Car
  - "03001627" # Chair
  - "04379243" # Table
  # - "03636649" # Lamp

image:
  channels: 3
  size: 224

sdf:
  num_samples: 2048

pointcloud:
  filename: "model_normalized.ply"
  max_points: 4096
